# ESPHome LVGL Chart Widget Examples
# =============================================================================
# LVGL v9.4 Chart Widget - Complete Examples
#
# Chart Types: LINE, BAR, SCATTER, NONE
# Update Modes: SHIFT (sliding window), CIRCULAR (ECG-style)
# Axes: PRIMARY_Y, SECONDARY_Y, PRIMARY_X, SECONDARY_X
#
# Actions:
#   - lvgl.chart.set_next_value: Add point (uses SHIFT/CIRCULAR mode)
#   - lvgl.chart.set_value_by_id: Set specific point by index
#   - lvgl.chart.set_value_by_id2: Set X/Y for scatter charts
#   - lvgl.chart.set_series_color: Change series color dynamically
#   - lvgl.chart.refresh: Refresh chart display
# =============================================================================

# =============================================================================
# EXAMPLE 1: Simple Weather Chart with Home Assistant
# =============================================================================
# This is the simplest example - temperature and humidity on one chart

sensor:
  - platform: homeassistant
    id: weather_temp
    entity_id: weather.forecast_maison
    attribute: temperature
    on_value:
      then:
        # IMPORTANT: Label ID must match the label defined in widgets!
        - lvgl.label.update:
            id: temp_label
            text:
              format: "%.1f°C"
              args: [id(weather_temp).state]
        - lvgl.chart.set_next_value:
            id: weather_chart
            series_id: temp_series
            value: !lambda 'return (int)id(weather_temp).state;'

  - platform: homeassistant
    id: weather_humidity
    entity_id: weather.forecast_maison
    attribute: humidity
    on_value:
      then:
        - lvgl.label.update:
            id: humidity_label
            text:
              format: "%.0f%%"
              args: [id(weather_humidity).state]
        - lvgl.chart.set_next_value:
            id: weather_chart
            series_id: humidity_series
            value: !lambda 'return (int)id(weather_humidity).state;'

lvgl:
  displays:
    - display_id: my_display
      pages:
        # =====================================================================
        # PAGE 1: Weather Chart (LINE) - Most Common Use Case
        # =====================================================================
        - id: weather_page
          bg_color: 0x000000
          widgets:
            # Current temperature label
            - label:
                id: temp_label           # Must match sensor on_value!
                x: 20
                y: 10
                width: 100
                text: "--.-°C"           # Initial placeholder
                text_color: 0xFF0000

            # Current humidity label
            - label:
                id: humidity_label       # Must match sensor on_value!
                x: 130
                y: 10
                width: 100
                text: "--%"              # Initial placeholder
                text_color: 0x0000FF

            # Weather line chart
            - chart:
                id: weather_chart
                x: 20
                y: 50
                width: 400
                height: 180
                type: LINE
                point_count: 24          # 24 data points
                update_mode: SHIFT       # New points push old ones left
                bg_color: 0x1a1a2e
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 4
                div_line_count_ver: 6
                items:
                  line_width: 2
                indicator:
                  radius: 3
                axis_primary_y:
                  min_value: -10
                  max_value: 40
                axis_secondary_y:
                  min_value: 0
                  max_value: 100
                series:
                  - id: temp_series
                    color: 0xFF0000      # Red for temperature
                    axis: PRIMARY_Y
                  - id: humidity_series
                    color: 0x0000FF      # Blue for humidity
                    axis: SECONDARY_Y

        # =====================================================================
        # PAGE 2: Scatter Chart - STATIC (no animation)
        # =====================================================================
        - id: scatter_page
          bg_color: 0x1a1a2e
          widgets:
            - label:
                x: 20
                y: 10
                text: "Scatter Chart (Static)"
                text_color: 0xFFFFFF

            # Scatter chart - static points defined in x_points/y_points
            - chart:
                id: scatter_chart
                x: 50
                y: 50
                width: 250
                height: 250
                type: SCATTER
                point_count: 10
                bg_color: 0x0a0a14
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 5
                div_line_count_ver: 5
                items:
                  line_width: 0          # No lines between points
                indicator:
                  bg_color: 0xFF6600
                  radius: 6              # Point size
                axis_primary_y:
                  min_value: 0
                  max_value: 100
                axis_primary_x:
                  min_value: 0
                  max_value: 100
                series:
                  - id: scatter_series
                    color: 0xFF6600
                    # Static X/Y coordinates
                    x_points: [10, 20, 30, 40, 50, 60, 70, 80, 90, 95]
                    y_points: [15, 35, 25, 55, 45, 75, 65, 85, 70, 90]

        # =====================================================================
        # PAGE 3: Bar Chart with Initial Data
        # =====================================================================
        - id: bar_page
          bg_color: 0x1a1a2e
          widgets:
            - label:
                x: 20
                y: 10
                text: "Monthly Data (BAR)"
                text_color: 0xFFFFFF

            - chart:
                id: bar_chart
                x: 20
                y: 50
                width: 400
                height: 200
                type: BAR
                point_count: 12
                bg_color: 0x0a0a14
                border_width: 1
                border_color: 0x333333
                div_line_count_hor: 5
                div_line_count_ver: 12
                items:
                  bg_opa: 80%
                axis_primary_y:
                  min_value: 0
                  max_value: 500
                series:
                  - id: bar_series
                    color: 0x4CAF50
                    # Initial bar values
                    points: [120, 180, 240, 200, 280, 350, 420, 380, 320, 290, 250, 200]

# =============================================================================
# OPTIONAL: Animations (uncomment to enable)
# =============================================================================
# If you want to animate the scatter chart, uncomment this interval:
#
# globals:
#   - id: scatter_angle
#     type: float
#     initial_value: "0"
#
# interval:
#   - interval: 50ms
#     then:
#       - lambda: |-
#           id(scatter_angle) += 0.1;
#           if (id(scatter_angle) > 6.28) id(scatter_angle) = 0;
#       - lvgl.chart.set_value_by_id2:
#           id: scatter_chart
#           series_id: scatter_series
#           point_index: 0
#           x_value: !lambda 'return 50 + (int)(40 * cos(id(scatter_angle)));'
#           y_value: !lambda 'return 50 + (int)(40 * sin(id(scatter_angle)));'

# =============================================================================
# TROUBLESHOOTING
# =============================================================================
#
# Labels show "--" or placeholder text:
#   - Check that entity_id exists in Home Assistant
#   - Check that attribute name is correct (temperature, humidity, etc.)
#   - Make sure label ID in on_value matches label ID in widgets
#   - Check ESPHome logs for sensor values
#
# Chart doesn't update:
#   - Make sure series_id matches the series defined in the chart
#   - Check that the chart ID is correct
#   - Verify sensor is receiving data (check logs)
#
# Scatter animation not working:
#   - Make sure globals and interval sections are uncommented
#   - Verify point_index is within range (0 to point_count-1)
